services:
  tts_backend:
    build:
      context: ./backend/text_to_speech_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/text_to_speech_api
          target: /app
          action: sync

  llm_api:
    build:
      context: ./backend/llm_api
    ports:
      - "8001:8000"
    env_file:
      - ./backend/llm_api/.env
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/llm_api
          target: /app
          action: sync

  # scrape_ingest:
  #   build:
  #     context: ./backend/scrape_ingest
  #   ports:
  #     - "8002:8000"
  #   env_file:
  #     - ./backend/scrape_ingest/.env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   develop:
  #     watch:
  #       - path: ./backend/scrape_ingest
  #         target: /app
  #         action: sync

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:80"
  #   develop:
  #     watch:
  #       - path: ./frontend
  #         target: /usr/share/nginx/html
  #         action: sync
