services:
  tts_backend:
    build:
      context: ./backend/text_to_speech_api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/text_to_speech_api/.env
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/text_to_speech_api
          target: /app
          action: sync

  llm_api:
    build:
      context: ./backend/llm_api
    ports:
      - "8001:8000"
    env_file:
      - ./backend/llm_api/.env
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/llm_api
          target: /app
          action: sync

  # ───────── NEW: Sea Lion Chat API ─────────
  chat_api:
    build:
      context: ./backend/chat_api
    ports:
      - "8003:8000"
    env_file:
      - ./backend/chat_api/.env
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/chat_api
          target: /app
          action: sync
    restart: unless-stopped
