services:
  backend:
    build:
      context: ./backend/text_to_speech_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - path: ./backend/text_to_speech_api
          target: /app
          action: sync

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    develop:
      watch:
        - path: ./frontend
          target: /usr/share/nginx/html
          action: sync
